# Generated by Django 6.0 on 2025-12-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='personal_devices',
            field=models.TextField(blank=True, help_text='Count or details of personal devices', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='staff_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
