# Generated by Django 6.0 on 2025-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='reminder_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
