# Generated by Django 6.0 on 2025-12-11 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemnotification_notificationeventsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationeventsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertoolaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mni', models.CharField(max_length=50, unique=True, verbose_name='MNI')),
                ('device_type', models.CharField(default='Laptop', max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='In Store', max_length=50)),
                ('signed', models.CharField(blank=True, default='-', max_length=50)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('location', models.CharField(choices=[('Dubai', 'Dubai Device List'), ('India', 'India Device List'), ('Pakistan', 'Pakistan Device List'), ('Staff', 'Staff List')], default='Dubai', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
