# Generated by Django 6.0 on 2025-12-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notificationeventsetting_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
