# Generated by Django 6.0 on 2025-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_contacts',
            field=models.BooleanField(default=False),
        ),
    ]
