# Generated by Django 6.0 on 2025-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_can_manage_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_manage_contacts',
        ),
        migrations.AlterField(
            model_name='notificationeventsetting',
            name='event_type',
            field=models.CharField(choices=[('USER_ADDED', 'New User Added'), ('ASSET_UPDATE', 'Asset Added/Updated'), ('SIG_CREATED', 'Email Signature Created'), ('TIMESHEET_SUBMITTED', 'Timesheet Submitted'), ('TIMESHEET_REJECTED', 'Timesheet Rejected'), ('TIMESHEET_APPROVED', 'Timesheet Approved')], max_length=20, unique=True),
        ),
    ]
