# Generated by Django 6.0 on 2025-12-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userprofile_can_manage_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique key for the feature flag', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Global switch for this feature')),
                ('description', models.TextField(blank=True, help_text='What does this feature do?')),
            ],
        ),
    ]
