# Generated by Django 6.0 on 2025-12-24 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notificationeventsetting_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationeventsetting',
            name='email_subscribers',
            field=models.ManyToManyField(blank=True, related_name='email_notification_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
