# Generated by Django 6.0 on 2025-12-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notificationeventsetting_email_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationeventsetting',
            name='event_type',
            field=models.CharField(choices=[('USER_ADDED', 'New User Added'), ('ASSET_UPDATE', 'Asset Added/Updated'), ('SIG_CREATED', 'Email Signature Created'), ('TIMESHEET_SUBMITTED', 'Timesheet Submitted'), ('TIMESHEET_REJECTED', 'Timesheet Rejected'), ('TIMESHEET_APPROVED', 'Timesheet Approved'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_STATUS_CHANGED', 'Ticket Status Changed'), ('TICKET_CANCELLED', 'Ticket Cancelled'), ('TICKET_COMPLETED', 'Ticket Completed'), ('TICKET_COMMENTED', 'Ticket Commented')], max_length=50, unique=True),
        ),
    ]
