# Generated by Django 6.0 on 2025-12-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_notificationeventsetting_email_subscribers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.CharField(help_text='Email ID', max_length=255)),
                ('email_host_password', models.CharField(help_text='App Password', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
