# Generated by Django 6.0 on 2025-12-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_emailconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationeventsetting',
            name='event_type',
            field=models.CharField(choices=[('USER_ADDED', 'New User Added'), ('ASSET_UPDATE', 'Asset Added/Updated'), ('SIG_CREATED', 'Email Signature Created'), ('TIMESHEET_SUBMITTED', 'Timesheet Submitted'), ('TIMESHEET_REJECTED', 'Timesheet Rejected'), ('TIMESHEET_APPROVED', 'Timesheet Approved'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_STATUS_CHANGED', 'Ticket Status Changed'), ('TICKET_COMMENTED', 'Ticket Commented'), ('TICKET_BREACHED', 'Ticket SLA Breached'), ('TICKET_BREACH_WARNING', 'Ticket Breach Warning (1h Before)'), ('USER_APPROVED', 'User Account Approved'), ('USER_REJECTED', 'User Account Rejected'), ('USER_TOOL_ACCESS', 'User Tool Permission Granted'), ('SYSTEM_HIGH_LOAD', 'High System Load (>500 Users)'), ('SYSTEM_ERROR_SPIKE', 'System Error Spike'), ('SYSTEM_DOWNTIME', 'System App Issue/Downtime')], max_length=50, unique=True),
        ),
    ]
