# Generated by Django 6.0 on 2025-12-10 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mni', models.CharField(blank=True, help_text='Inventory ID', max_length=50)),
                ('assigned_to_email', models.EmailField(blank=True, help_text='Fallback if user not in system', max_length=254, null=True)),
                ('device_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('MONITOR', 'Monitor'), ('MOUSE', 'Mouse'), ('KEYBOARD', 'Keyboard'), ('HEADPHONE', 'Headphone'), ('OTHER', 'Other')], default='LAPTOP', max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model_detail', models.CharField(help_text='Detail/Specs', max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('os_type', models.CharField(choices=[('MAC', 'MacOS / iOS'), ('WINDOWS', 'Windows'), ('ANDROID', 'Android'), ('LINUX', 'Linux'), ('NONE', 'N/A')], default='NONE', help_text='For statistics', max_length=10)),
                ('status', models.CharField(choices=[('IN_USE', 'In Use'), ('IN_STORE', 'In Store / Available'), ('DAMAGED', 'Damaged'), ('REPAIR', 'Under Repair'), ('LOST', 'Lost/Stolen')], default='IN_STORE', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Status/Remarks')),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff in Possession', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
