# Generated by Django 6.0 on 2025-12-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_signed',
            field=models.BooleanField(default=False, help_text='Signed For'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(choices=[('DUBAI', 'Dubai'), ('INDIA', 'India'), ('PAKISTAN', 'Pakistan')], default='DUBAI', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(help_text='Serial Number/Device ID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_USE', 'Company Asset'), ('IN_STORE', 'In Store'), ('DAMAGED', 'Damaged'), ('REPAIR', 'Under Repair'), ('LOST', 'Lost/Stolen')], default='IN_STORE', max_length=20),
        ),
    ]
