# Generated by Django 6.0 on 2025-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('MAC', 'Mac'), ('IPHONE', 'iPhone'), ('OTHER', 'Other')], default='LAPTOP', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_USE', 'Company Asset'), ('IN_STORE', 'In Store'), ('DAMAGED', 'Damaged'), ('REPAIR', 'Under Repair'), ('LOST', 'Lost/Stolen')], default='IN_STORE', max_length=20),
        ),
    ]
