# Generated by Django 6.0 on 2025-12-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('MAC', 'Mac'), ('IPHONE', 'iPhone'), ('DAMAGED', 'Damaged'), ('REPLACEMENT', 'Replacement'), ('RESIGNED', 'Resigned'), ('OTHER', 'Other')], default='LAPTOP', max_length=20),
        ),
    ]
