# Generated by Django 6.0 on 2025-12-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_edited_by',
            field=models.CharField(blank=True, help_text='User who last edited this asset', max_length=150),
        ),
    ]
