# Generated by Django 6.0 on 2025-12-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(help_text='Serial Number/Device ID', max_length=100),
        ),
    ]
