# Generated by Django 6.0 on 2026-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_asset_last_audited_alter_asset_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MACBOOK', 'Mac book'), ('IPHONE', 'iPhone'), ('ANDROID', 'Android Phone'), ('KEYBOARD_MOUSE', 'Keyboard and Mouse'), ('DAMAGED', 'Damaged'), ('REPLACEMENT', 'Replacement'), ('RESIGNED', 'Resigned'), ('OTHER', 'Other')], default='LAPTOP', max_length=20),
        ),
    ]
