# Generated by Django 6.0 on 2026-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_asset_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MACBOOK', 'Mac book'), ('IPHONE', 'iPhone'), ('ANDROID', 'Android Phone'), ('KEYBOARD_MOUSE', 'Keyboard and Mouse'), ('OTHER', 'Other')], default='LAPTOP', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_USE', 'Company Asset'), ('IN_STORE', 'In Store'), ('DAMAGED', 'Damaged'), ('REPLACEMENT', 'Replacement'), ('RESIGNED', 'Resigned'), ('REPAIR', 'Under Repair'), ('LOST', 'Lost/Stolen')], default='IN_STORE', max_length=20),
        ),
    ]
