# Generated by Django 6.0 on 2026-01-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_asset_device_type_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='Date when asset was returned/resigned', null=True),
        ),
    ]
