# Generated by Django 6.0 on 2026-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_asset_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MACBOOK', 'Mac book'), ('IPHONE', 'iPhone'), ('ANDROID', 'Android Phone'), ('KEYBOARD_MOUSE', 'Keyboard and Mouse'), ('MONITOR', 'Monitor'), ('OTHER', 'Other')], default='LAPTOP', max_length=20),
        ),
    ]
