# Generated by Django 6.0 on 2025-12-12 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetconfiguration',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='timesheetconfiguration',
            name='user',
        ),
        migrations.CreateModel(
            name='EmployeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hr_admin', models.BooleanField(default=False, help_text='Can approve/reject timesheets and manage HR settings.')),
                ('requires_timesheet', models.BooleanField(default=True, help_text='If True, this user must submit timesheets.')),
                ('timesheet_enabled', models.BooleanField(default=False, help_text='If True, user can access the punch in/out system.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('IN', 'Punch In'), ('OUT', 'Punch Out')], max_length=3)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_manual_entry', models.BooleanField(default=False, help_text='True if added by HR manually.')),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='First day of the month')),
                ('period_end', models.DateField(help_text='Last day of the month')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('employee', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_punch_in', models.TimeField(blank=True, null=True)),
                ('last_punch_out', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('WEEK_OFF', 'Week Off'), ('HOLIDAY', 'Holiday'), ('LEAVE', 'On Leave')], default='ABSENT', max_length=20)),
                ('is_manual_adjustment', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hr.timesheet')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('timesheet', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='TimesheetConfiguration',
        ),
    ]
