# Generated by Django 6.0 on 2025-12-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_timesheetconfiguration_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdailyentry',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('WEEK_OFF', 'Week Off'), ('HOLIDAY', 'Holiday'), ('SICK_LEAVE', 'Sick Leave'), ('ANNUAL_LEAVE', 'Annual Leave'), ('WFH', 'Work From Home')], default='ABSENT', max_length=20),
        ),
    ]
