# Generated by Django 6.0 on 2025-12-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_timesheetdailyentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesettings',
            name='allow_edit',
            field=models.BooleanField(default=True, help_text='If False, user cannot edit entries (requires strict mode flag).'),
        ),
        migrations.AddField(
            model_name='employeesettings',
            name='allow_punch',
            field=models.BooleanField(default=True, help_text='If False, user cannot punch (requires strict mode flag).'),
        ),
    ]
