# Generated by Django 6.0 on 2025-12-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_restore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfiguration',
            name='email_files_only',
            field=models.BooleanField(default=False, help_text='Send email only if files are backed up? Or maybe attach files? Assuming notification config.'),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='retention_days',
            field=models.IntegerField(default=30, help_text='Number of days to keep backups'),
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='daily', max_length=20),
        ),
    ]
