# Generated by Django 6.0 on 2025-12-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_restore', '0002_backupconfiguration_email_files_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='backup_type',
            field=models.CharField(choices=[('full', 'Full System'), ('file', 'File Only')], default='full', max_length=10),
        ),
    ]
