# Generated by Django 6.0 on 2025-12-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, help_text='Admin resolution notes', null=True),
        ),
    ]
