# Generated by Django 6.0 on 2025-12-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_status_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for the ticket', null=True),
        ),
    ]
