# Generated by Django 6.0 on 2025-12-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
