# Generated by Django 6.0 on 2025-12-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning Sent'), ('BREACHED', 'Breach Notified')], default='NORMAL', max_length=20),
        ),
    ]
